version: '3.8'

services:
  mysql:
    image: mysql:latest      
    container_name: mysql-container  
    environment:
      MYSQL_ROOT_PASSWORD: 12345  
      MYSQL_DATABASE: localhost1        
      MYSQL_USER: mysql            
      MYSQL_PASSWORD: mysql      
    ports:
      - "3307:3306"        
    volumes:
      - ./dados_mysql:/var/lib/mysql  
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
